GET http://localhost:5000/

###
POST http://localhost:5000/login
content-type: application/json

{
    "username": "admin",
    "password": "thisisthepass"
}

###
POST http://localhost:5000/register
content-type: application/json

{
    "username": "admin",
    "password": "thisisthepassword"
}

###
GET http://localhost:5000/admin/adminpanel
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjE3NTg1NTg5fQ.OoXeFQY1TudnHiu6EbVfz-rlQdLcEE59u7Kr5EDoqOY



