GET http://localhost:5000/

###
POST http://localhost:5000/login
content-type: application/json

{
    "username": "admin",
    "password": "thisisthepass"
}

###
POST http://localhost:5000/register
content-type: application/json

{
    "username": "admin",
    "password": "thisisthepassword"
}

###
GET http://localhost:5000/adminpanel
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6InRlc3QiLCJpYXQiOjE2MTc1ODQwMzZ9.UDqtZ1xuTjlND0LGJilrx0fTk5qfmj9m-jNCBd4cvek